title: Xanarciz.github.io
email: xanarciz@gmail.com
description: >-
  Blog tempat Xanarciz menulis.
baseurl: "/"
url: ""
twitter_username: xanarciz
github_username:  xanarciz
permalink: /:title.html

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
